version: '3'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/the_comic_stand_club
    depends_on:
      - db

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: the_comic_stand_club_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
