"""empty message

Revision ID: 683aeb9c502a
Revises: 2a7b7dd86a2e
Create Date: 2023-05-18 13:00:37.646602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683aeb9c502a'
down_revision = '2a7b7dd86a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_club_memberships_club_id', 'club_memberships', type_='foreignkey')
    op.drop_constraint('fk_club_memberships_user_id', 'club_memberships', type_='foreignkey')
    op.create_foreign_key('fk_club_memberships_club_id', 'club_memberships', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_club_memberships_user_id', 'club_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_club_memberships_club_id', 'club_memberships', type_='foreignkey')
    op.drop_constraint('fk_club_memberships_user_id', 'club_memberships', type_='foreignkey')
    op.create_foreign_key('fk_club_memberships_club_id', 'club_memberships', 'clubs', ['club_id'], ['id'])
    op.create_foreign_key('fk_club_memberships_user_id', 'club_memberships', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###