"""empty message

Revision ID: 2a7b7dd86a2e
Revises: 9cc01f9a2dcc
Create Date: 2023-05-18 12:54:25.821236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7b7dd86a2e'
down_revision = '9cc01f9a2dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_memberships', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_memberships', 'status')
    # ### end Alembic commands ###